### ISSUE TITLE
timeline feature

### ISSUE THREAD

**Issue by toenobu** [mmurak/eurythm#1]
Hi, 

this is my first question on github. こんにちは、ライオン英語チャネルからきました。

wavesurfer をドキュメントを見たのですが、 timeline の機能を導入する予定はありますか？
https://wavesurfer.xyz/examples/?timeline.js

**Comment by mmurak** [comment]
timelineは入れた方がいいでしょうか？　確かに目安になるのですが、再生速度を変更した場合でもオリジナルの秒数のまま変わらないという点が少し気になっています。

**Comment by mmurak** [comment]
とは言うものの、入れてみました。😇

**Comment by toenobu** [comment]
すみません、ありがとうございます 🙇‍♂️ 不評でしたら、廃止してください。

## ユーザーの機能要望の導入について
一度、導入した機能を消すは、難しいことは理解しているつもりです。
要望の一つのとしてあげて、要望が多ければ実装にしてほしいくらいの感覚でした。
催促してしまったみたいで、すみません。上にも書いてますが、不評でしたら、削除してください 🙇 

以下のブログが、サービスのカスタマイズ ついて述べていておもしろいので、よかったら読んでみてください。
http://nmi.jp/2016-10-27-Customizing-for-B2B

## Context と pain point 
すみません、context が大事でした。
自分の使い方は、主に dictation で使っています。2-3分くらいの音源を10秒くらい間隔に区切って、再生スピードを落としながら使ってます。波形を元にして、10秒くらいで区切りを探すのですが、それがわかりにくいのが自分のペインポイントでした。あやまってリロードしたときなど、復元したりするときに困っていました。timeline feature の導入で解決できました。

> 再生速度を変更した場合でもオリジナルの秒数のまま変わらないという点が少し気になっています。

この懸念は、オリジナルの秒数のままの方がうれしいのが個人的な意見でした。

## お礼
元々dropbox の audio player を利用していましたが、指定区間の repeat のおかげで dictation が楽になりました。ありがとうございます。plugin をいろいろとみていて、以下のサイトの、region 機能もいいなと思ったので、PR or issues を 送るかもしれないです。

https://wavesurfer.xyz/example/annotation/

**Comment by mmurak** [comment]
Timelineについては本日公開した Eurythm Double では開発当初から実装していたので、ある意味において整合性が取れたと言えるのかもしれません（Doubleは「モデル音源と生徒様のシャドーイング音源を逐次的に比較、コメントしていく際にEurythmを2つ起動し、ブラウザのタブを切り替えながら作業を進めるのが煩雑だ」というサラ先生からのニーズがあったため［専門家向け機能的な意味合いで］Timelineを入れていたのでした）。

不評が高まれば、起動時パラメータ等で切り替えられるようにするということは可能ですし。
---
A-B間ループを実装する際、region機能も検討したのですが、今ひとつしっくり感じるインターフェースを思い浮かべることができなかったので（^^;）、割と古典的な手法で解決することにしました。

それでは、また何か要望等がありましたら、どうぞお気軽に連絡してください。
😇
